### ISSUE TITLE
Mouse up error with Leaflet 1.8

### ISSUE THREAD

**Issue by andreavillaservitly** [sandropibia/Leaflet.SelectAreaFeature#14]
The event mouseUp (when selecting an area) keeps triggering the error:

core.js:6498 ERROR TypeError: Cannot use 'in' operator to search for '_leaflet_id' in 
    at o (leaflet-src.js:68:10)
    at t.hasLayer (leaflet-src.js:6681:12)
    at t._doMouseUp (Leaflet.SelectAreaFeature.js:73:19)
    at t.fire (leaflet-src.js:613:13)
    at t._fireDOMEvent (leaflet-src.js:4419:17)
    at t._handleDOMEvent (leaflet-src.js:4368:10)
    at HTMLDivElement.s (leaflet-src.js:2692:15)
    at c.invokeTask (zone.js:406:37)
    at Object.onInvokeTask (core.js:28668:33)
    at c.invokeTask (zone.js:405:60)

This only happens with Leaflet v1.8, with previous ones is still working.

**Comment by rmcf** [comment]
@sandropibia 
Same for me:

Uncaught TypeError: Cannot use 'in' operator to search for '_leaflet_id' in 
    at stamp (leaflet-src.js?8d6f:68:1)
    at NewClass.hasLayer (leaflet-src.js?8d6f:6934:1)
    at NewClass._doMouseUp (Leaflet.SelectAreaFeature.js?5406:73:1)
    at NewClass.fire (leaflet-src.js?8d6f:606:1)
    at NewClass._fireDOMEvent (leaflet-src.js?8d6f:4565:1)
    at NewClass._fireEvent (leaflet-src.js?8d6f:12922:1)
    at NewClass._onClick (leaflet-src.js?8d6f:12867:1)
    at HTMLCanvasElement.handler (leaflet-src.js?8d6f:2799:1)

**Comment by sandropibia** [comment]
Have found the issue:
1. that the mousemove function is on even user releaves mouse button
2. can't remove the layer inside map, because it is not present, then the mouse move event is drawing lines. 

I'm looking for solution and test it for relase 1.9.

**Comment by sandropibia** [comment]
New release is added. Please test it @rmcf

**Comment by giorgiopiazzasy** [comment]
Could you please push the update on NPM? Still not working on leaflet 1.9.4

**Comment by sandropibia** [comment]
A new version is now published to NPM, check it please
